"""Generate report figures directly from repository datasets (no external data)."""

from __future__ import annotations

import csv
import html
from collections import Counter, defaultdict
from pathlib import Path
from statistics import mean


ROOT = Path(__file__).resolve().parents[1]
ASSETS = ROOT / "docs" / "report_assets"
SYNTHETIC = ROOT / "AI_Module" / "AIML" / "dataset_generator" / "generated_dataset.csv"
REPLAY = ROOT / "backend" / "data" / "processed_driver_features.csv"

COLORS = {"0": "#38c6b1", "1": "#f4af4d", "2": "#e96172"}
LABELS = {"0": "Class 0 · Normal", "1": "Class 1 · Warning", "2": "Class 2 · Legacy high-risk scenario"}


def write(path: Path, text: str) -> None:
    path.write_text(text, encoding="utf-8")


def svg_wrap(title: str, body: str, subtitle: str) -> str:
    return f'''<svg xmlns="http://www.w3.org/2000/svg" width="1600" height="900" viewBox="0 0 1600 900">
<rect width="1600" height="900" fill="#f6fafc"/>
<rect x="0" y="0" width="1600" height="130" fill="#092d4c"/>
<text x="70" y="62" fill="#ffffff" font-family="Arial, sans-serif" font-size="34" font-weight="700">{html.escape(title)}</text>
<text x="70" y="103" fill="#9fdfdc" font-family="Arial, sans-serif" font-size="20">{html.escape(subtitle)}</text>
{body}
<text x="70" y="860" fill="#637b89" font-family="Arial, sans-serif" font-size="17">Source: repository dataset analysis generated by tools/generate_report_assets.py · 21 August 2026</text>
</svg>'''


def class_summary(rows: list[dict[str, str]]) -> str:
    counts = Counter(row["condition_label"] for row in rows)
    features = ["heart_rate_bpm", "sweat_microsiemens", "skin_temp_celsius", "grip_force_newton"]
    groups: dict[str, dict[str, list[float]]] = defaultdict(lambda: defaultdict(list))
    for row in rows:
        label = row["condition_label"]
        for feature in features:
            groups[label][feature].append(float(row[feature]))
    max_count = max(counts.values())
    body = ["<text x='70' y='180' fill='#0a3153' font-family='Arial' font-size='24' font-weight='700'>Samples by synthetic scenario label</text>"]
    for i, label in enumerate(("0", "1", "2")):
        y = 235 + i * 105
        width = 560 * counts[label] / max_count
        body.append(f"<text x='70' y='{y}' fill='#193d55' font-family='Arial' font-size='21'>{LABELS[label]}</text>")
        body.append(f"<rect x='390' y='{y-25}' width='{width:.1f}' height='36' rx='8' fill='{COLORS[label]}'/>")
        body.append(f"<text x='{405+width:.1f}' y='{y+1}' fill='#193d55' font-family='Arial' font-size='20' font-weight='700'>{counts[label]:,} samples</text>")
    body.append("<rect x='930' y='166' width='600' height='510' rx='14' fill='#ffffff' stroke='#c9dce5'/>")
    body.append("<text x='970' y='215' fill='#0a3153' font-family='Arial' font-size='24' font-weight='700'>Mean measurements by scenario</text>")
    body.append("<text x='970' y='250' fill='#637b89' font-family='Arial' font-size='17'>All values below are from synthetic generator output.</text>")
    headers = ["Scenario", "HR (bpm)", "EDA (µS)", "Temp (°C)", "Grip (N)"]
    for j, label in enumerate(headers):
        body.append(f"<text x='{970 + [0,155,275,395,510][j]}' y='300' fill='#07877f' font-family='Arial' font-size='17' font-weight='700'>{label}</text>")
    for i, label in enumerate(("0", "1", "2")):
        y = 365 + i * 95
        values = [mean(groups[label][feature]) for feature in features]
        body.append(f"<rect x='963' y='{y-35}' width='530' height='62' rx='7' fill='{COLORS[label]}' fill-opacity='.11'/>")
        row = [LABELS[label].split(' · ')[1], *(f"{value:.2f}" for value in values)]
        xs = [970,1125,1245,1365,1480]
        for x, value in zip(xs, row):
            body.append(f"<text x='{x}' y='{y}' fill='#193d55' font-family='Arial' font-size='18'>{html.escape(value)}</text>")
    body.append("<text x='70' y='610' fill='#0a3153' font-family='Arial' font-size='23' font-weight='700'>Dataset card</text>")
    card = ["90,000 rows", "10 synthetic driver IDs", "3 balanced classes", "9 physiology/ECG features"]
    for i, item in enumerate(card):
        x = 70 + i * 205
        body.append(f"<rect x='{x}' y='645' width='180' height='90' rx='12' fill='#e9f8f6' stroke='#b8e3df'/>")
        body.append(f"<text x='{x+18}' y='683' fill='#07877f' font-family='Arial' font-size='21' font-weight='700'>{item}</text>")
    body.append("<text x='70' y='790' fill='#8e4b1d' font-family='Arial' font-size='18'>Interpretation: these classes are generated scenarios, not clinical labels or real-driver outcomes.</text>")
    return svg_wrap("Synthetic Dataset Study — Distribution and Scenario Means", "".join(body), "AI_Module/AIML/dataset_generator/generated_dataset.csv")


def points(values: list[float], x: float, y: float, width: float, height: float) -> str:
    low, high = min(values), max(values)
    spread = high - low or 1.0
    return " ".join(f"{x + i * width / (len(values)-1):.1f},{y + height - (v-low) / spread * height:.1f}" for i, v in enumerate(values))


def replay_timeline(rows: list[dict[str, str]]) -> str:
    features = [("hr_rolling_mean", "Heart rate (bpm)", "#0c78b7"), ("gsr_rolling_mean", "GSR / EDA (µS)", "#e89b35"), ("temp_rolling_mean", "Skin temperature (°C)", "#dc5b6d")]
    body = ["<text x='70' y='180' fill='#0a3153' font-family='Arial' font-size='24' font-weight='700'>Rolling telemetry replay — 296 time-indexed rows</text>"]
    for i, (field, label, color) in enumerate(features):
        top = 225 + i * 175
        values = [float(row[field]) for row in rows]
        body.append(f"<rect x='70' y='{top}' width='1460' height='130' rx='10' fill='#ffffff' stroke='#c9dce5'/>")
        for step in range(1, 4):
            gy = top + step * 32
            body.append(f"<line x1='160' y1='{gy}' x2='1480' y2='{gy}' stroke='#e2edf2' stroke-width='1'/>")
        body.append(f"<text x='90' y='{top+42}' fill='#193d55' font-family='Arial' font-size='19' font-weight='700'>{label}</text>")
        body.append(f"<text x='90' y='{top+70}' fill='#637b89' font-family='Arial' font-size='16'>min {min(values):.2f} · mean {mean(values):.2f} · max {max(values):.2f}</text>")
        body.append(f"<polyline points='{points(values, 250, top+15, 1230, 96)}' fill='none' stroke='{color}' stroke-width='3' stroke-linejoin='round'/>")
    counts = Counter(row["condition_label"] for row in rows)
    body.append("<text x='70' y='770' fill='#0a3153' font-family='Arial' font-size='23' font-weight='700'>Replay label composition</text>")
    body.append(f"<text x='70' y='808' fill='#637b89' font-family='Arial' font-size='19'>Class 0: {counts['0']} rows · Class 1: {counts['1']} rows · Class 2: {counts['2']} rows</text>")
    body.append("<text x='70' y='838' fill='#8e4b1d' font-family='Arial' font-size='17'>The data was created from the project’s synthetic scenario generator; trend shape is evidence of replay behaviour, not human physiology.</text>")
    return svg_wrap("Replay Dataset Study — Rolling Signal Trends", "".join(body), "backend/data/processed_driver_features.csv")


def main() -> None:
    ASSETS.mkdir(parents=True, exist_ok=True)
    with SYNTHETIC.open(newline="", encoding="utf-8") as handle:
        synthetic_rows = list(csv.DictReader(handle))
    with REPLAY.open(newline="", encoding="utf-8") as handle:
        replay_rows = list(csv.DictReader(handle))
    write(ASSETS / "synthetic_dataset_study.svg", class_summary(synthetic_rows))
    write(ASSETS / "replay_timeline_study.svg", replay_timeline(replay_rows))
    summary = {
        "synthetic_dataset_rows": len(synthetic_rows),
        "synthetic_label_counts": dict(Counter(row["condition_label"] for row in synthetic_rows)),
        "replay_dataset_rows": len(replay_rows),
        "replay_label_counts": dict(Counter(row["condition_label"] for row in replay_rows)),
    }
    write(ASSETS / "dataset_summary.txt", "\n".join(f"{key}: {value}" for key, value in summary.items()) + "\n")


if __name__ == "__main__":
    main()
